### PR TITLE
Plugin Hooks

### PR DESCRIPTION
**Pull request by luisc99**
Adds a hook system, which can allow optional integrations with other plugins. All functionality is maintained when any hooked plugins are not installed.

This also includes a hook for WorldGuard, which prevents an entity from being caught if the player does not have build access to a region. [This feature was requested on the feedback site](https://feedback.songoda.com/d/448-worldguard-integration), and other protection plugins can be added using the same process

I purposefully coded this in this way to allow for expansion of the hook system if others have any other features they wish to include in it

### CODE REVIEW

**Comment by briannastatic** [comment]
Great commit! We have a worldguard multi compatibility class in SongodaCore. If you wanna use that rather than hooking into worldguard directly I'll approve the commit. If you don't have time I can do this for you as well.

**Comment by luisc99** [comment]
I can't believe I didn't notice that! I totally agree that would probably be a better implementation. If you wish to do it that'd be great (you'll know your code better than me), but I can add it in if you're busy

**Comment by briannastatic** [comment]
I'll add it in for you ^-^

**Comment by briannastatic** [comment]
Hey sorry, had a little bit of things to do.

I cleaned up your commit:
- Made it so other plugins can add support without us needing to hard code it.
- Removed direct and specific WorldGuard support in exchange for SongodaCores built in multi version support.
- Added general support for the few protection plugins we support in SongodaCore.

If you disagree with anything let me know. I'll give you a few hours before I have this tested and released.

Thanks for your contribution!

**Comment by luisc99** [comment]
I don't seem to be able to see your changes, but those points sound perfect! Thanks :)

(Actually I see them now in your other branch, it looks great)

**Comment by briannastatic** [comment]
I got a bit to do and I’m done for the night. If you wanna test it and make sure it’s solid that would be great help.

**Comment by luisc99** [comment]
That seems to work fine with no hooks installed, however when I tried it with WorldGuard it seemed to trip up on the check in SongodaCore ([specifically this line](https://github.com/songoda/SongodaCore/blob/b72bf6fc2813ee807962f569d2646222a2742c1c/Core/src/main/java/com/songoda/core/hooks/worldguard/WorldGuardFlagHandler.java#L235)). There needs to be a player object passed to that to check against, which I didn't notice before. It's probably best to pass the player to [the isBuildAllowed](https://github.com/songoda/SongodaCore/blob/b72bf6fc2813ee807962f569d2646222a2742c1c/Core/src/main/java/com/songoda/core/hooks/WorldGuardHook.java#L100) function in WorldGuardHook, and use a slightly modified getBooleanFlag which accepts a player argument.

This is the trace if it helps:
```
[16:47:43] [Server thread/ERROR]: Could not pass event ProjectileHitEvent to UltimateCatcher v1.4.5
java.lang.NullPointerException: The build flag is handled in a special fashion and requires a non-null subject parameter
	at com.sk89q.worldguard.protection.FlagValueCalculator.queryAllValues(FlagValueCalculator.java:277) ~[?:?]
	at com.sk89q.worldguard.protection.FlagValueCalculator.queryValue(FlagValueCalculator.java:223) ~[?:?]
	at com.sk89q.worldguard.protection.FlagValueCalculator.queryState(FlagValueCalculator.java:170) ~[?:?]
	at com.sk89q.worldguard.protection.RegionResultSet.queryState(RegionResultSet.java:97) ~[?:?]
	at com.songoda.ultimatecatcher.core.hooks.worldguard.WorldGuardFlagHandler.getBooleanFlag(WorldGuardFlagHandler.java:235) ~[?:?]
	at com.songoda.ultimatecatcher.core.hooks.WorldGuardHook.isBuildAllowed(WorldGuardHook.java:101) ~[?:?]
	at com.songoda.ultimatecatcher.hook.hooks.WorldGuardHook.shouldStopCapture(WorldGuardHook.java:12) ~[?:?]
	at com.songoda.ultimatecatcher.hook.ExternalHookManager.shouldStopCapture(ExternalHookManager.java:27) ~[?:?]
	at com.songoda.ultimatecatcher.listeners.EntityListeners.onSmack(EntityListeners.java:242) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor309.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-400]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-400]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1317) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:121) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.EntityEgg.a(EntityEgg.java:32) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.EntityProjectile.tick(EntityProjectile.java:53) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:845) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.World.a(World.java:886) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:530) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1351) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1204) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-400]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-400]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

I've not tested the other protection hooks yet (I've never used them in the past), but might be able to give them a go later on if I get time

**Comment by briannastatic** [comment]
Sorry haven't had time to work on this. Any chance you could fix this yourself? If not, I'll get to it eventually. Sorry for the wait though!

**Comment by luisc99** [comment]
Of course. I didn't do it before to avoid having to create a secondary PR for SongodaCore (and because my maven is being weird with that repo), but it should be an easy fix.

That change here, plus the one in core, should work. I'm unable to compile/test it though as maven is being weird trying to get all the dependencies right for core, probably my internet breaking again, so you might need to test it on your end and make sure that didn't break anything with the rest of the hooks

Edit: I was able to test this a few days later, from what I can tell it works exactly like it should

**Comment by luisc99** [comment]
Hey! I know you said you were busy recently, but I was wondering if there was any updates on merging these? It'd be a handy update in getting the plugin working properly again on my server

**Comment by briannastatic** [comment]
Fixed it up. Releasing shortly <3 Thanks!

**Pull request closed without merging**
